name: Build ISO

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
      - uses: actions/checkout@v3

      - name: Install debootstrap/git
        run: apt update && apt install git debootstrap -y

      - name: Build ISO
        run: |
          cd /
          git clone https://github.com/jiafeitech/cvm-ui-desktop.git
          cd cvm-ui-desktop
          ./build.sh etc/terraform-azure.conf

      - uses: actions/upload-artifact@v3
        with:
          name: Cvm UI Desktop 5.2
          path: /cvm-ui-desktop/builds/
